### ISSUE TITLE
Cannot install translations plugin

### ISSUE THREAD

**Issue by unnisathyarajan** [coralproject/talk-recipes#5]
Hi

I tried to install the translation plugin in talk and it is not picking. 

I tried the basic setup as per the documentation - tried both on docker and source - the talk service is not picking it up. 

Anyone pls advice.

**Comment by kgardnr** [comment]
Hey @unnisathyarajan! Welcome to Talk!

Did you follow these instructions here: https://github.com/coralproject/talk/blob/master/README.md

The translations are not a plugin, they're actually built into core. Are you trying to add a translation? 

Can you let me know some more details so I can better help guide you?

**Comment by unnisathyarajan** [comment]
Hello @kgardnr 
we successfully setup talk and everything is working fine.

we are trying to translate the embed comment module so we tried using a translation yml file and we also tried using the example translations recipe plugin. Both tries failed although we can see in the logs that the plugin we added is being recognized.

we followed the instructions in https://coralproject.github.io/talk/plugins/ for deploying the recipe translations plugin and followed the instructions in https://coralproject.github.io/talk/installation-from-docker/ to set the TALK_DEFAULT_LANG variable on build.

**Comment by kgardnr** [comment]
Oh I see - so the `translations` recipe here is to OVERRIDE existing translations. 

You want to check this out: https://github.com/coralproject/talk/tree/master/locales

Talk supports multiple languages out of the box.

If you have a new language that isn't there, you'll want to submit a pull request with that new language.

Does that make sense?

**Comment by unnisathyarajan** [comment]
yes, I have seen the supported locales but we do require new ones that are not available out of the box.

our use case is as follows; our website supports multiple RTL languages in addition to English. what we are trying to do is to only translate the frontend user-facing embed comment module and not the whole interface. 

we will be keeping the admin interface in English but require the website users to input in different languages such as English, Arabic, and Urdu.

**Comment by kgardnr** [comment]
Oh great! So yes, what you need to do is contribute these translations. You can choose which parts you want to translate - for example, just translating the user-facing stream copy.

**Comment by unnisathyarajan** [comment]
sure we will definitely contribute these translations but the technical issue is that we even tried to test the out of the box locales (eg fr) and it didn't work.

We tried with docker to set the translation to french as per documentation and it did not work.
[docker build -t my-awesome-talk-image --build-arg TALK_DEFAULT_LANG=fr .](https://coralproject.github.io/talk/installation-from-docker/)

Also tried to do a source build with TALK_DEFAULT_LANG set to fr. Didn't work.

**Comment by kgardnr** [comment]
Great, we can't wait to see your contributions!

In regards to setting the default language - can you try setting `fr` in your local storage in your browser, and let me know if that works correctly?

**Comment by kgardnr** [comment]
FYI, if you don't know how to do this you can type this into your console:

```
localStorage.setItem('locale', 'fr')
```

**Comment by unnisathyarajan** [comment]
Thanks a lot, Kim that worked!!
